language: javascript

cache:
  directories:
    - "travis_phantomjs"

before_install:
  - mkdir qunit
  - wget -O qunit/qunit-1.18.0.css http://code.jquery.com/qunit/qunit-1.18.0.css
  - wget -O qunit/qunit-1.18.0.js  http://code.jquery.com/qunit/qunit-1.18.0.js
  - mkdir -p travis_phantomjs
  - if [ ! -f $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi;
  - if [ ! -f $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs ]; then tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs; fi;
  - npm install testem

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

script:
  - ./node_modules/.bin/testem -t www/tests/qunit/run_tests.html ci
  #- phantomjs phantomjs/examples/run-qunit.js www/tests/qunit/run_tests.html

